@startuml updatedModel
abstract class CustomModel {
    + {abstract} fields: CustomModelField[]
    + rights: string[]
    + title: string
    + matSortActive: string

    + {static} apiToModel(objectFromApi: any): CustomModel
    + modelToApi(): Object
    + getDateOffset(year: number, month: number, day: number): Date
    + getIdentifyingName(): string
    + get<T = CustomModel>(field: string): T
    + set(field: string, value: any): CustomModel
    + getOptions(field: string): CustomModel[]
    + setOptions(field: string, value: any[])
    + add(field: string, value: any)
    + isPrintable(): boolean
    + isAssignable(): boolean
    + isCheckable(): boolean
    
}

class CustomModelField<T> {
    + value: T
    + title: string
    + kindOfField: string
    + isDisplayedInSummary: boolean
    + isDisplayedInModal: boolean
    + isDisplayedInTable: boolean
    + isImageInTable: boolean
    + isRequired: boolean
    + isSettable: boolean
    + isEditable: boolean
    + nullValue: string
    + hint: string
    + patternError: string
    + pattern: string
    + isTrigger: boolean
    + triggerFunction: Function
    + filterName: string
    
    + {static} fillWithDefault(properties: Object)
    + formatForApi()
}

CustomModelField *-- "0-*" CustomModel
@enduml