export const TEXT = {
    country_khm : 'Cambodia',
    country_syr : 'Syria',
    country_lbn : 'Lebanon',
    
    dashboard_distribution_map : 'خريطة التوزيع',
    dashboard_summary : 'الملخص',
    dashboard_summary_1 : 'مجموع المستفيدين',
    dashboard_summary_2 : 'المشاريع الناشطة',
    dashboard_summary_3 : 'المستفيدين المسجلين',
    dashboard_summary_4 : ' القيمة الإجمالية للمعملات',
    dashboard_recent_distributions : 'التوزيعات الحديثة',

    menu_home : 'الصفحة الرئيسية',
    menu_projects : 'المشاريع',
    menu_beneficiaries : 'المستفيدون',
    menu_reports : 'التقارير',
    menu_settings : 'الإعدادات',

    header_home : 'الصفحة الرئيسية',
    header_projects : 'المشاريع',
    'header_add-distribution' : 'إضافة توزيع',
    'header_distributions' : 'التوزيع',
    'header_update-beneficiary' : 'تحديث المستفيد',
    header_beneficiaries : 'المستفيدون',
    header_resports : 'التقارير',
    header_settings : 'الإعدادات',
    header_reports : 'التقارير',
    header_profile : ' المعطيات الشخصية',
    header_import :  'تحميل بيانات المستفيد',
    'header_data-validation' : 'التأكد من صحة البيانات',
    'header_add-beneficiaries' : 'إضافة المستفيد',
    header_disconnect :  'تسجيل الخروج من الحساب',
    header_language : 'اللغة',
    header_imported: 'إستيراد بيانات المستفيدين',

    login_title : ' تسجيل الدخول الى الحساب',
    login_bms : 'نظام إدارة المستفيدين',
    login_username : 'اسم المستخدم',
    login_password : 'كلمة المرور',
    login_login : 'تسجيل الدخول الى الحساب',
    login_forgot_password : 'هل نسيت كلمة المرور',

    settings_title : 'الإعدادات',
    settings_users : 'المستخدمون',
    settings_country_specific_options : 'الخيارات حسب البلد',
    settings_donors : 'المانحين',
    settings_projects : 'المشاريع',
    settings_export : 'تحميل',

    report_title : 'الرسوم البيانية',
    report_filter_per_year : 'حسب كل سنة ',
    report_filter_per_quarter : 'حسب كل ربع سنة',
    report_filter_per_month : 'حسب كل شهر',
    report_filter_chose_periode : 'اختر الفترة',
    report_export : 'تحميل',
    report_from : 'من',
    report_to : 'إلى',
    report_apply : 'تطبيق',
    report_select_frequency : 'اختر التكرار',
    report_frequency_year : ' حسب السنة  ',
    report_frequency_quarter : 'حسب ربع السنة ',
    report_frequency_month : ' حسب الشهر',
    report_period_selected : 'حسب الفترة المختارة',
    report_country_report : 'الرسوم البيانية حسب البلد',
    report_project_report : 'الرسوم البيانية حسب المشروع',
    report_distribution_report : 'الرسوم البيانية حسب التوزيع',
    report_country : ' البلد',
    report_project :  'المشروع',
    report_distribution : ' التوزيع',
    report_upcoming_reporting : 'الرسوم البيانية القادمة',
    report_loader : 'التحميل',

    beneficiaries_title : 'المستفيدون',
    beneficiaries_export : 'تحميل',

    beneficiaries_import : 'تحميل',
    beneficiaries_import_file : 'تحميل من ملف',
    beneficiaries_import_api : 'تحميل من مصدر بيانات خارجي',
    beneficiaries_select_api : 'API اختر',
    beneficiaries_import_title: 'تحميل بيانات المستفيد',
    beneficiaries_import_getProject: 'المشاريع',
    beneficiaries_import_csv: 'csv تنزيل ملف',
    beneficiaries_import_addFile: ' إضافة ملف أو وضع ملف ',
    beneficiaries_import_upload: 'تحميل',

    add_beneficiary_title: 'إضافة مستفيد',
    add_beneficiary_step1: 'معلومات',
    add_beneficiary_step2: 'رب العائلة',
    add_beneficiary_step3:'أفراد العائلة',
    add_beneficiary_step4: 'النهاية', 
    add_beneficiary_done: 'ملخص معطيات المستفيد قبل اضافته', 
    add_beneficiary_create: 'إنشاء',
    add_beneficiary_cancel: 'إلغاء',
    add_beneficiary_next: 'التالي',
    add_beneficiary_getProject: 'المشاريع',
    add_beneficiary_getProvince: 'المحافظة',
    add_beneficiary_getDistrict: 'المنطقة',
    add_beneficiary_getCommune: 'البلدية',
    add_beneficiary_getVillage: 'القرية',
    add_beneficiary_getAddressNumber: 'رقم الشارع ',
    add_beneficiary_getAddressStreet: 'اسم الشارع ',
    add_beneficiary_getAddressPostcode: 'عنوان البريدي',
    add_beneficiary_getNotes : 'ملاحظات',
    add_beneficiary_getFamilyName : 'اللقب',
    add_beneficiary_getGivenName : 'الاسم',
    add_beneficiary_getGender : 'الجنس',
    add_beneficiary_getDateOfBirth : 'تاريخ الميلاد',
    add_beneficiary_getNationalID : 'رقم الهوية الوطنية',
    add_beneficiary_getOccupation : 'الوظيفة',
    add_beneficiary_getTypeNationalId: 'نوع الهوية الوطنية',
    add_beneficiary_getTypePhone: 'نوع الهاتف',
    add_beneficiary_getPhone: 'الهاتف',
    add_beneficiary_Country_Specifics: 'معطيات البلد',

    update_beneficiary_title: 'تحديث المستفيدين',

    data_verification_title: 'التحقق من صحة البيانات و الموافقة',
    data_verification_step_1: 'أخطاء في كتابة المعلومات', 
    data_verification_step_2: 'التأكد من التكرار',
    data_verification_step_3: 'للإضافة',
    data_verification_step_4: 'للحذف',
    data_verification_step_5: 'النهاية', 
    data_verification_step_1_no_issues: 'لا يوجد أخطاء في كتابة المعلومات', 
    data_verification_step_2_no_issues: 'لا يوجد تكرار في كتابة المعلومات',
    data_verification_step_3_no_issues: 'لا يوجد مستفيدون للإضافة',
    data_verification_step_4_no_issues: 'لا يوجد مستفيدون للحذف',
    data_verification_done: 'تم التحقق من بياناتك',
    data_verification_chip_existing: 'موجد',
    data_verification_chip_new: 'جديد',
    data_verification_chip_old: 'قديم',
    data_verification_chip_add: 'للإضافة',
    data_verification_chip_remove: 'للحذف',
    data_verification_next: 'التالي',
    data_verification_send: 'أرسل',
    data_verification_snackbar_typo_corrected: 'أخطاء الكتابة التي تم تصحيحها', 
    data_verification_snackbar_typo_no_corrected: 'كل أخطاء الكتابة التي لم يتم تصحيحها',
    data_verification_snackbar_duplicate_corrected: 'أخطاء التكرار المصححة',
    data_verification_snackbar_duplicate_no_corrected: 'كل أخطاء التكرار التي لم يتم تصحيحها',
    data_verification_snackbar_less_corrected: 'تم حذف المستفيدين بنجاح',
    data_verification_snackbar_more_corrected: 'تم إضافة المستفيدين بنجاح',

    distribution_title : 'التوزيعات',
    distribution_export : 'تحميل',
    project_title: 'المشاريع',

    add_project_title : 'مشروع جديد',
    add_project_new_distribution : 'توزيعة جديدة',
    add_distribution_selection_criteria : 'معيار الاختيار',
    add_distribution_distributed_commodity : 'السلع الموزعة',
    add_distribution_beneficiaries_reached: 'المستفيدون الذين تم الوصول إليهم',
    add_distribution_households_reached: 'الأسر التي تم الوصول إليها',
    add_distribution_commodities_delivered: 'تم اعطاء',
    add_distribution_threshold: ' المجموع الادنى لاختيار ',
    add_distribution_text_explanation: 'سيختار النظام فقط المستفيدين / الأسر التي لديها مجموع أعلى من المجموع الادنى ',
    add_distribution_female: 'المرأة',
    add_distribution_male: 'الرجل',
    add_project: 'إنشاء مشروع',

    table_filter : 'البحث عن طريق الكلمات الرئيسية',
    table_actions : 'اجراءات',
    table_items_per_page : 'العناصر في كل صفحة',
    table_first_page : 'الصفحة الأولى',
    table_previous_page : 'الصفحة السابقة',
    table_next_page : 'الصفحة التالية',
    table_last_page : 'الصفحة الاخيرة',
    table_of_page : 'من',
    table_quantity : 'الكمية',

    modal_details_title : 'تفاصيل',
    modal_update_title : 'تحديث',
    modal_add_title : 'إضافة جديد',
    modal_delete_title : 'حذف',
    modal_language_title : 'اللغة',
    modal_language_actual : 'اللغة الحالية',
    modal_delete_sentence : 'أنت على وشك الحذف',
    modal_delete_sentence_2 : 'هل أنت متأكد',
    modal_close : 'إغلاق',
    modal_cancel : 'إلغاء',
    modal_save : 'حفظ',
    modal_delete : 'حذف',
    modal_create : 'إنشاء',
    modal_add : 'إضافة',
    modal_valid_email : 'من فضلك أدخل البريد الكتروني الصحيح',
    modal_email_is : 'البريد الالكتروني هو',
    modal_email_placeholder : 'البريد الالكتروني',
    modal_required : 'مطلوب',
    modal_leave : 'المغادرة',
    modal_leave_sentence : 'هل تريد حقا أن تغادر دون حفظ التغييرات',

    model_country_specific : 'خيار حسب بالبلد',
    model_country_specific_field: 'الميدان',
    model_country_specific_type: 'النوع',
    model_country_specific_countryIso3: 'البلد',
    model_distribution : 'التوزيع',
    model_distribution_name: 'الاسم',
    model_distribution_location_name: 'الموقع',
    model_distribution_number_beneficiaries: 'عدد المستفيدين',
    model_distribution_sectors_name: 'القطاعات',
    model_distribution_adm1: 'المحافظة',
    model_distribution_adm2: 'المنطقة',
    model_distribution_adm3: 'البلدية',
    model_distribution_adm4: 'القرية',
    model_distribution_date: 'تاريخ التوزيع',
    model_donor : 'المانح', 
    model_donor_fullname: 'اسم المانح',
    model_donor_shortname: 'الاسم المختصر',
    model_donor_notes: 'الملاحظات',
    model_donor_projects_name: 'المشاريع',
    model_households : 'الأسرة',
    model_beneficiaries_familyName: 'اللقب',
    model_beneficiaries_firstName: 'الاسم ',
    model_beneficiaries_location: 'الموقع',
    model_beneficiaries_dependents : 'التوابع',
    model_beneficiaries_vulnerabilities : 'نقاط الضعف',
    model_beneficiaries_projects : 'المشاريع',
    model_beneficiaries_gender : 'الجنس',
    model_beneficiaries_dateofbirth : 'تاريخ الميلاد',
    model_beneficiaries_status : 'الرتبة في الأسرة',
    model_beneficiaries_nationalids: 'رقم الهوية',
    model_beneficiaries_phones: 'الهاتف',
    model_beneficiaries_pickupDate: 'Pick up date',
    model_beneficiaries_message: 'Message',
    model_user : 'المستخدم',
    model_user_username: 'الريد الاكتروني',
    model_user_password: 'كلمة المرور',
    model_user_rights: 'الحقوق',
    model_project : 'المشروع',
    model_project_name: 'اسم المشروع',
    model_project_sectors_name: 'القطاعات',
    model_project_start_date: 'تاريخ البداية',
    model_project_end_date: 'تاريخ الانتهاء',
    model_project_number_of_households: 'عدد الأسر',
    model_project_donors_name: 'المانحون',
    model_project_notes: 'الملاحظات',
    model_project_value: 'المبلغ الموزع',
    model_sector : 'القطاع',
    model_criteria : 'المعاير',
    model_criteria_kind_beneficiary : 'المجموعة',
    model_criteria_field : 'المعايير',
    model_criteria_operator : 'الشروط',
    model_criteria_value : 'القيمة',
    model_criteria_beneficiary : 'المستفيد',
    model_criteria_household : 'الأسرة',
    model_criteria_weight : 'وزن النتيجة',
    model_commodity: 'السلع',
    model_commodity_modality: 'القيد',
    model_commodity_type: 'نوع',
    model_commodity_unit: 'وحدة',
    model_commodity_value: 'كمية',
    model_commodity_currency: 'العملة',
    model_beneficiaries_state: 'الحالة',
    model_beneficiaries_values: 'القيمة',
    sample_choose_size: 'حجم العينة',


    import_added: 'تم إضافتها',
    import_deleted: 'تم حذفها',
    import_created: 'تم إنشاؤها',
    import_updated: 'تم تحديثها',
    import_description: 'قم باستيراد الملف الذي يحتوي على التوزيع المعدّل. سيتم تحديث قاعدة البيانات بقائمة المستفيدين الجديدة لهذا التوزيع عندما تنقر على ""تحديث"" بعد الاستيراد.',

    distribution_details_export: 'قائمة التوزيع',
    distribution_details_import: 'تحميل والمقارنة',
    distribution_details_random: 'عينة عشوائية للتحميل',
    distribution_details_validate: 'التحقق والقفل',
    transaction_amount_total: 'الكمية الإجمالية',
    transaction_amount_done: 'الكمية المرسلة',
    transaction_amount_waiting: 'ما زال يتعين إرسالها',
    transaction_prevention: 'This platform is still under development and the online cash transaction functionality may not be fully stable yet. The development team denies responsibility for any errors that may occur in terms of money loss. By ticking the box below, you agree to use the system knowing fully well its limitations and take responsibility for the results of the transaction.',
    transaction_accept_prevention: 'I agree to these terms.',

    profile_user_information: 'معلومات المستخدم',
    profile_user_change_password: 'تغيير كلمة المرور',
    profile_user_hint_old_password: 'كلمة المرور القديمة',
    profile_user_hint_new_password: 'كلمة المرور الجديدة',
    profile_user_hint_new_password_again: 'أعد إدخال كلمة المرور الجديدة',
    snackbar_change_password_done: '!تم تغيير كلمة المرور',
    snackbar_change_password_fail: '...لا يمكن تغيير كلمة المرور',
    snackbar_change_password_not_possible: 'يجب أن تكون كلمة المرور أطول من حرف واحد وتتطابق مع الشروط',

    forbidden: 'الصفحة ممنوعة',
    forbidden_message: 'عذرا , ليس لديك إذن للدخول إلى هذه الصفحة',
    not_found: 'الصفحة غير موجودة',
    not_found_message: 'عذرا , لا يمكن العثور على هذه الصفحة',
    back_to_homepage: 'العودة إلى الصفحة الرئيسية',

    role_user_admin: 'مسؤول',
    role_user_read_only: 'قراءة فقط',
    role_user_field_officer: 'مسؤول عن الميدان',
    role_user_project_officer: 'عنصر في مشروع',
    role_user_project_manager: 'مسؤول عن مشروع',
    role_user_country_manager: 'مسؤول عن البلد',
    role_user_regional_manager: 'مسؤول عن الإقليم',
    role_user_global_admin: 'المسؤول العام',

    no_data: 'لايوجد بيانات',
    modal_add_no_value: 'عليك بادخال قيمة عددية',
    modal_add_fail_criteria: 'خطأ في انشاء معيار',
    modal_add_bad_weight: 'يجب أن يكون الوزن أكبر من 0',
    modal_add_invalid_mail: ' عليك بادخال البريد الالكتروني ',
    modal_add_no_password: 'عليك بادخال كلمة المرور ',
    modal_add_no_right: 'عليك بتحديد الحق',
    modal_no_project: 'عليك بتحديد مشروع على الأقل يتعلق بالحق',
    modal_no_country: 'عليك بتحديد بلد على الأقل يتعلق بالحق',
    modal_check_fields: 'تحقق جيدا انك أدخلت جميع المعطيات',
    modal_add_check_fields_budget: 'تحقق جيدا انك أدخلت جميع المعطيات و ان المبلغ يفوق 0',
    modal_check_date: 'الحقول غير الصالحة: لا يمكن أن يكون تاريخ الانتهاء  أقدم من تاريخ البدء',
    modal_add_check_fields_quantity: 'تحقق جيدا انك أدخلت جميع المعطيات و ان الكمية تفوق 0 ',

    table_element_deleted: ' تم حذفها',
    table_element_updated: ' تم تحديثها',

    error_interceptor_msg: '(وقع خطأ : لا يمكن الاستجابة (محتوى فارغ',

    beneficiaries_import_select_project: 'يجب أن تختار مشروعا و ملفا قبل التحميل',
    beneficiaries_import_error_importing: 'وقع خطأ عندالتحميل البيانات',
    beneficiaries_import_beneficiaries_imported: 'تم إضافة المستفيدين ',
    beneficiaries_import_check_fields: ' محتوى فارغ , تثبت من أدخال جميع المعطيات و اختيار مشروع ',

    beneficiaries_added: 'تم إضافة المستفيدين الى المشروع',

    data_verification_error: 'حدث خطأ في معالجة البيانات',
    data_verification_chip_actual: 'المنزل المستهدف',
    data_verification_description1: 'تعرض هذه اللوحة أي أخطاء كتابة مشكوك فيها تتعلق بالمستفيدين في ملفك: إذا كان المستفيد المستورد يتطابق بشكل وثيق مع آخر موجود بالفعل في قاعدة البيانات ، فسيتم عرضه هنا. يمكنك اختيار إما الحفاظ على القائمة ، وتحديثها مع البيانات المستوردة أو حفظ كلاهما كمستفيدين منفصلين.',
    data_verification_description2: 'تعرض لوحة التكرار المستفيدين في الملف الموجودين بالفعل في قاعدة البيانات في منزل آخر. إذا كان المستفيد الحالي ليس رب أسرة ، يمكنك حذف احداهما ، أو حفظ كلاهما كمستفيدين مختلفين إذا كنت متأكداً من أنهم أشخاص مختلفون.',
    data_verification_description3: '.في ما يلي قائمة بالأسر المدرجة  في قاعدة البيانات ولكن مع عدد أقل من المستفيدين مقارنة بالملف المستورد. يمكنك التحقق وتحديد الذين تريد استيرادهم في المنزل',
    data_verification_description4: '.في ما يلي قائمة بالأسر المدرجة  في قاعدة البيانات ولكن مع عدد أكبر  من المستفيدين مقارنة بالملف المستورد. يمكنك التحقق وتحديد الذين تريد استيرادهم في المنزل',

    update_beneficiary_check_steps: 'البيانات المطلوبة غير كاملة أو غير صالحة: يرجى التحقق من جميع المراحل',
    update_beneficiary_created_successfully: 'تم الإنشاء بنجاح!',
    update_beneficiary_error_creating: ': حدث خطأ أثناء الإنشاء ',
    update_beneficiary_updated_successfully: ' !تم التحديث بنجاح',
    update_beneficiary_error_updated: ': حدث خطأ أثناء التحديث',

    add_distribution_check_date: '  mm / dd / yyyyy  حدث خطأ أثناء حفظ التاريخ ، تحقق من أن التنسيق يشبه',
    add_distribution_date_inside_project: 'خطأ أثناء إنشاء توزيع جديد ، يجب أن يكون تاريخ التوزيع الخاص بك داخل تواريخ المشروع',
    add_distribution_distribution: 'التوزيع: ',
    add_distribution_created: 'تم انشائه',
    add_distribution_error_creating: 'خطأ أثناء إنشاء توزيع جديد',
    add_distribution_check_fields: 'إملء معلومات التوزيع الجديدة  قبل ، بما في ذلك قيمة السلع والقيمة الأدنى يجب أن تكون أعلى من 0.',

    distribution_validated: ' تم التحقق من صحة التوزيع',
    distribution_not_validated: 'لا يمكن التحقق من صحة التوزيع ',
    distribution_no_right_validate: 'لا يحق لك التحقق من صحة التوزيع ، اسأل مدير المشروع الخاص بك',
    distribution_no_valid_commodity: 'لم يتم اكتشاف سلعة صالحة لهذا التوزيع',
    distribution_wrong_mail: 'بريد إلكتروني خاطئ',
    distribution_no_right_transaction: 'لا يحق لك أن تقوم بالصفقة ، اسأل مدير المشروع الخاص بك أو مدير بلدك',
    distribution_beneficiary_added: 'تم أضافة المستفيد',
    distribution_beneficiary_not_added: 'لم بتم أضافة المستفيد',
    distribution_request_logs: 'Send transaction logs by email',
    refresh_transaction: 'Check pickup status',

    import_distribution_updated: 'تم تحديث التوزيع',
    import_distribution_no_right_update: 'لا يحق لك تحديث التوزيع ، اسأل مدير المشروع الخاص بك',

    settings_project_exists: 'مشروع بهذا الاسم يوجود بالفعل',
    settings_created: 'تم انشاء ',

    model_distribution_type: 'العالمي',

    projects_distribution_title: 'العالمي',

    beneficiaries_add_list: 'العالمي',
};