export const TEXT = {
    dashboard_distribution_map : 'distribution map',
    dashboard_country_program : 'cambodia programs',
    dashboard_summary : 'summary',
    dashboard_summary_1 : 'total beneficiaries',
    dashboard_summary_2 : 'active projects',
    dashboard_summary_3 : 'enrolled beneficiaries',
    dashboard_summary_4 : 'total value transactions',
    dashboard_recent_distributions : 'recent distributions',

    menu_home : 'home',
    menu_projects : 'projects',
    menu_beneficiaries : 'beneficiaries',
    menu_reports : 'reports',
    menu_settings : 'settings',

    header_home : 'Home',
    header_projects : 'Projects',
    'header_add-distribution' : 'Add Distribution',
    'header_distributions' : 'Distribution',
    header_beneficiaries : 'Beneficiaries',
    header_resports : 'Reports',
    header_settings : 'Settings',
    header_profile : 'Profile',
    header_import : 'Import',
    'header_data-validation' : 'Data Validation',
    'header_add-beneficiaries' : 'Add Household',
    header_disconnect : 'log out',
    header_language : 'language',

    login_title : 'login',
    login_bms : 'Beneficiary management system',
    login_username : 'username',
    login_password : '*********',
    login_login : 'login',
    login_forgot_password : 'Forgot password ?',

    settings_title : 'settings',
    settings_users : 'users',
    settings_country_specific_options : 'country specific options',
    settings_donors : 'donors',
    settings_projects : 'projects',
    settings_export : 'export',

    report_title : 'reports',
    report_filter_per_year : 'per year',
    report_filter_per_quarter : 'per quarter',
    report_filter_per_month : 'per month',
    report_filter_chose_periode : 'choose period',
    report_export : 'export',
    report_from : 'from',
    report_to : 'to',
    report_apply : 'apply',
    report_select_frequency : 'Select frequency',
    report_frequency_year : 'Year',
    report_frequency_quarter : 'Quarter',
    report_frequency_month : 'Month',
    report_period_selected : 'Period selected',
    report_country_report : 'country report',
    report_project_report : 'project report',
    report_distribution_report : 'distribution report',
    report_country : 'country',
    report_project : 'project',
    report_distribution : 'distribution',
    report_upcoming_reporting : 'Upcoming reporting',
    report_loader : 'Loader',

    beneficiaries_title : 'beneficiaries',
    beneficiaries_export : 'export',

    beneficiaries_import : 'import',
    beneficiaries_import_file : 'file import',
    beneficiaries_import_api : 'api import',
    beneficiaries_select_api : 'Select API',
    beneficiaries_import_title: 'import households data',
    beneficiaries_import_getProject: 'Projects',
    beneficiaries_import_csv: 'download csv template',
    beneficiaries_import_addFile: 'add file or drag and drop',
    beneficiaries_import_upload: 'upload',

    add_beneficiary_title: 'add beneficiary',
    add_beneficiary_step1: 'Information',
    add_beneficiary_step2: 'Head',
    add_beneficiary_step3: 'Members',
    add_beneficiary_step4: 'Done',
    add_beneficiary_done: 'Summary of Household to create',
    add_beneficiary_create: 'Create',
    add_beneficiary_cancel: 'Cancel',
    add_beneficiary_next: 'Next',
    add_beneficiary_getProject: 'Projects',
    add_beneficiary_getProvince: 'Province',
    add_beneficiary_getDistrict: 'District',
    add_beneficiary_getCommune: 'Commune',
    add_beneficiary_getVillage: 'Village',
    add_beneficiary_getAddressNumber: 'Address Number',
    add_beneficiary_getAddressStreet: 'Address Street',
    add_beneficiary_getAddressPostcode: 'Address Postcode',
    add_beneficiary_getNotes : 'Notes',
    add_beneficiary_getFamilyName : 'Family Name',
    add_beneficiary_getGivenName : 'Given Name',
    add_beneficiary_getGender : 'Gender',
    add_beneficiary_getDateOfBirth : 'Date of Birth',
    add_beneficiary_getNationalID : 'National ID Number',
    add_beneficiary_getOccupation : 'Livelihood',
    add_beneficiary_getTypeNationalId: 'Type of National ID Number',
    add_beneficiary_getTypePhone: 'Type phone',
    add_beneficiary_getPhone: 'Phone',
    add_beneficiary_Country_Specifics: 'Country Specifics',

    update_beneficiary_title: 'Update Beneficiary',

    data_verification_title: 'data verification and validation',
    data_verification_step_1: 'Typo issues',
    data_verification_step_2: 'Duplicates',
    data_verification_step_3: 'To add',
    data_verification_step_4: 'To remove',
    data_verification_step_5: 'Done',
    data_verification_step_1_no_issues: 'No typo issues',
    data_verification_step_2_no_issues: 'No duplicate',
    data_verification_step_3_no_issues: 'No beneficiaries to add',
    data_verification_step_4_no_issues: 'No beneficiaries to remove',
    data_verification_done: 'Your data has been verified',
    data_verification_chip_existing: 'Existing',
    data_verification_chip_new: 'New',
    data_verification_chip_old: 'Old',
    data_verification_chip_add: 'To add',
    data_verification_chip_remove: 'To remove',
    data_verification_next: 'Next',
    data_verification_send: 'Send',
    data_verification_snackbar_typo_corrected: 'Typo issues corrected',
    data_verification_snackbar_typo_no_corrected: 'All typo issues aren\'t corrected',
    data_verification_snackbar_duplicate_corrected: 'Duplicate issues corrected',
    data_verification_snackbar_duplicate_no_corrected: 'All duplicates aren\'t corrected',
    data_verification_snackbar_less_corrected: 'Beneficiaries removed with success',
    data_verification_snackbar_more_corrected: 'Beneficiaries added with success',

    distribution_title : 'distributions',
    distribution_export : 'export',
    project_title: 'projects',

    add_project_title : 'new project',
    add_project_new_distribution : 'new distribution',
    add_distribution_selection_criteria : 'selection criteria',
    add_distribution_distributed_commodity : 'distributed commodity',
    add_distribution_beneficiaries_reached: 'Beneficiaries reached',
    add_distribution_households_reached: 'Households reached',
    add_distribution_commodities_delivered: 'Commodities delivered',
    add_distribution_threshold: 'Minimum selection score',
    add_distribution_text_explanation: 'The system will only select beneficiaries/households that have a score higher than the minimum selection score',
    add_distribution_female: 'Woman',
    add_distribution_male: 'Man',
    add_project: 'Create a project',

    table_filter : 'Filter',
    table_actions : 'Actions',
    table_items_per_page : 'Items per page',
    table_first_page : 'First page',
    table_previous_page : 'Previous page',
    table_next_page : 'Next page',
    table_last_page : 'Last page',
    table_of_page : 'of',

    modal_details_title : 'Details',
    modal_update_title : 'Update',
    modal_add_title : 'Add a new ',
    modal_delete_title : 'Delete',
    modal_language_title : 'Language',
    modal_language_actual : 'Current language :',
    modal_delete_sentence : 'You are about to delete ',
    modal_delete_sentence_2 : '. Are you sure ? ',
    modal_close : 'Close',
    modal_cancel : 'Cancel',
    modal_save : 'Save',
    modal_delete : 'Delete',
    modal_create : 'Create',
    modal_valid_email : 'Please enter a valid email address',
    modal_email_is : 'Email is',
    modal_email_placeholder : 'Email',
    modal_required : 'required',
    modal_leave : 'Leave',
    modal_leave_sentence : 'Do you really want to leave with unsaved changes ?',

    model_country_specific : 'Country specific option',
    model_country_specific_field: 'Field',
    model_country_specific_type: 'Type',
    model_country_specific_countryIso3: 'Country',
    model_distribution : 'Distribution',
    model_distribution_name: 'Name',
    model_distribution_location_name: 'Location',
    model_distribution_number_beneficiaries: 'n° Beneficiaries',
    model_distribution_sectors_name: 'Sectors',
    model_distribution_adm1: 'Province',
    model_distribution_adm2: 'District',
    model_distribution_adm3: 'Community',
    model_distribution_adm4: 'Village',
    model_distribution_date: 'Date of distribution',
    model_donor : 'Donor',
    model_donor_fullname: 'Donor\'s name',
    model_donor_shortname: 'Shortname',
    model_donor_notes: 'Notes',
    model_donor_projects_name: 'Projects',
    model_households : 'Household',
    model_beneficiaries_familyName: 'Family name',
    model_beneficiaries_firstName: 'First name',
    model_beneficiaries_location: 'Location',
    model_beneficiaries_dependents : 'Dependents',
    model_beneficiaries_vulnerabilities : 'Vulnerabilities',
    model_beneficiaries_projects : 'Projects',
    model_beneficiaries_gender : 'Gender',
    model_beneficiaries_dateofbirth : 'Date of birth',
    model_beneficiaries_status : 'Satus',
    model_beneficiaries_nationalids: 'ID number',
    model_beneficiaries_phones: 'Phones',
    model_user : 'User',
    model_user_username: 'Email',
    model_user_password: 'Password',
    model_user_rights: 'Rights',
    model_project : 'Project',
    model_project_name: 'Project\'s name',
    model_project_sectors_name: 'Sectors',
    model_project_start_date: 'Start Date',
    model_project_end_date: 'End Date',
    model_project_number_of_households: 'Number of Households',
    model_project_donors_name: 'Donors',
    model_project_notes: 'Notes',
    model_project_value: 'Budget',
    model_sector : 'Sector',
    model_criteria : 'Criteria',
    model_criteria_kind_beneficiary : 'Group',
    model_criteria_field : 'Criteria',
    model_criteria_operator : 'Condition',
    model_criteria_value : 'Value',
    model_criteria_beneficiary : 'Beneficiary',
    model_criteria_household : 'Household',
    model_criteria_weight : 'Score weight',
    model_commodity: 'Commodity',
    model_commodity_modality: 'Modality',
    model_commodity_type: 'Type',
    model_commodity_unit: 'Unit',
    model_commodity_value: 'Quantity',
    model_commodity_currency: 'Currency',
    sample_choose_size: 'Sample size',


    import_added: 'Will be added',
    import_deleted: 'Will be deleted',
    import_errors: 'Will be ignored',
    import_description: 'Import the file that contains the modified distribution. The database will be updated with the new list of beneficiaries for this distribution when you will click on "update" after importing. Any unknown beneficiary will be ignored',

    distribution_details_export: 'export',
    distribution_details_import: 'import & compare',
    distribution_details_random: 'export random sample',
    distribution_details_validate: 'validate',

    profile_user_information: 'User information',
    profile_user_change_password: 'Change password',
    profile_user_hint_old_password: 'Old password',
    profile_user_hint_new_password: 'New password',
    profile_user_hint_new_password_again: 'Re-enter new password',
    snackbar_change_password_done: 'Password has been changed !',
    snackbar_change_password_fail: 'Could not change password...',
    snackbar_change_password_not_possible: 'Password must be longer than 1 character and match with verification',

    forbidden: 'Forbidden Page',
    forbidden_message: 'Sorry, you don\'t have permission to access this page',
    not_found: 'Page Not Found',
    not_found_message: 'Sorry, this page could not be found',
    back_to_homepage: 'Go back to homepage',

    role_user_admin: 'Administrator',
    role_user_read_only: 'Read only',
    role_user_field_officer: 'Field officer',
    role_user_project_officer: 'Project officer',
    role_user_project_manager: 'Project manager',
    role_user_country_manager: 'Country manager',
    role_user_regional_manager: 'Regional manager',
    role_user_global_admin: 'Global admin'
};
