export const TEXT = {
    // GENERAL VARIABLES

    // Utils
    add: 'Add',
    adm1: 'المحافظة',
    adm2: 'المنطقة',
    adm3: 'البلدية',
    adm4: 'القرية',
    back: 'Back',
    beneficiaries: 'المستفيدون',
    beneficiary: 'المستفيد',
    cancel: 'إلغاء',
    close: 'إغلاق',
    create: 'إنشاء',
    delete: 'حذف',
    details: 'تفاصيل',
    distribution: 'التوزيع',
    distributions: 'التوزيعات',
    done: 'النهاية',
    email: 'البريد الالكتروني',
    export: 'تحميل',
    gender: 'الجنس',
    home: 'الصفحة الرئيسية',
    households: 'الأسرة',
    import: 'تحميل',
    individual: 'Individual',
    location: 'الموقع',
    new: 'New',
    next: 'Next',
    no_data: 'لايوجد بيانات',
    phone: 'الهاتف',
    project: 'المشروع',
    projects: 'المشاريع',
    reports: 'التقارير',
    rights: 'الحقوق',
    save: 'حفظ',
    settings: 'الإعدادات',
    update: 'تحديث',

    // Error
    back_to_homepage: 'العودة إلى الصفحة الرئيسية',
    error_interceptor_msg: '(وقع خطأ: لا يمكن الاستجابة (محتوى فارغ',
    forbidden: 'الصفحة ممنوعة',
    forbidden_message: 'عذرا , ليس لديك إذن للدخول إلى هذه الصفحة',
    not_found: 'الصفحة غير موجودة',
    not_found_message: 'عذرا , لا يمكن العثور على هذه الصفحة',

    // Role
    role_user_admin: 'مسؤول',
    role_user_country_manager: 'مسؤول عن البلد',
    role_user_field_officer: 'مسؤول عن الميدان',
    role_user_project_manager: 'مسؤول عن مشروع',
    role_user_project_officer: 'عنصر في مشروع',
    role_user_regional_manager: 'مسؤول عن الإقليم',


    // SPECIFIC VARIABLES

    // Add beneficiary
    add_beneficiary_done: 'ملخص معطيات المستفيد قبل اضافته',
    add_beneficiary_getAddressNumber: 'رقم الشارع ',
    add_beneficiary_getAddressPostcode: 'عنوان البريدي',
    add_beneficiary_getAddressStreet: 'اسم الشارع ',
    add_beneficiary_getDateOfBirth: 'تاريخ الميلاد',
    add_beneficiary_getFamilyName: 'اللقب',
    add_beneficiary_getGivenName: 'الاسم',
    add_beneficiary_getNationalID: 'رقم الهوية الوطنية',
    add_beneficiary_getOccupation: 'الوظيفة',
    add_beneficiary_getTypeNationalId: 'نوع الهوية الوطنية',
    add_beneficiary_getTypePhone: 'نوع الهاتف',
    add_beneficiary_res_address: 'Resident Address',
    add_beneficiary_step1: 'معلومات',
    add_beneficiary_step2: 'رب العائلة',
    add_beneficiary_step3:'أفراد العائلة',
    add_beneficiary_title: 'إضافة مستفيد',

    // Add distribution
    add_distribution_beneficiaries_reached: 'المستفيدون الذين تم الوصول إليهم',
    add_distribution_check_date: '  mm / dd / yyyyy  حدث خطأ أثناء حفظ التاريخ ، تحقق من أن التنسيق يشبه',
    add_distribution_check_fields: 'إملء معلومات التوزيع الجديدة  قبل ، بما في ذلك قيمة السلع والقيمة الأدنى يجب أن تكون أعلى من 0.',
    add_distribution_commodities_delivered: 'تم اعطاء',
    add_distribution_created: 'تم انشائه',
    add_distribution_date_inside_project: 'خطأ أثناء إنشاء توزيع جديد ، يجب أن يكون تاريخ التوزيع الخاص بك داخل تواريخ المشروع',
    add_distribution_distributed_commodity: 'السلع الموزعة',
    add_distribution_error_creating: 'خطأ أثناء إنشاء توزيع جديد',
    add_distribution_female: 'المرأة',
    add_distribution_households_reached: 'الأسر التي تم الوصول إليها',
    add_distribution_male: 'الرجل',
    add_distribution_selection_criteria: 'معيار الاختيار',
    add_distribution_text_explanation: 'سيختار النظام فقط المستفيدين / الأسر التي لديها مجموع أعلى من المجموع الادنى ',
    add_distribution_threshold: ' المجموع الادنى لاختيار ',

    // Add project
    add_project_new_distribution: 'توزيعة جديدة',
    add_project_title: 'مشروع جديد',

    // Beneficiaries
    beneficiaries_add_distribution: 'Add beneficiaries to this distribution',
    beneficiaries_add_list: 'العالمي',
    beneficiaries_add_project: 'Please select the project(s) in which you would like to add the',
    beneficiaries_added: 'تم إضافة المستفيدين الى المشروع',
    beneficiaries_full_address: 'Full household address:',
    beneficiaries_household_info: 'Household information summary:',
    beneficiaries_import_addFile: ' إضافة ملف أو وضع ملف ',
    beneficiaries_import_api: 'تحميل من مصدر بيانات خارجي',
    beneficiaries_import_beneficiaries_imported: 'تم إضافة المستفيدين ',
    beneficiaries_import_check_fields: ' محتوى فارغ , تثبت من أدخال جميع المعطيات و اختيار مشروع ',
    beneficiaries_import_csv: ' تنزيل ملف',
    beneficiaries_import_error_importing: 'وقع خطأ عندالتحميل البيانات',
    beneficiaries_import_file: 'تحميل من ملف',
    beneficiaries_import_select_project: 'يجب أن تختار مشروعا و ملفا قبل التحميل',
    beneficiaries_import_title: 'تحميل بيانات المستفيد',
    beneficiaries_location: 'Household Location:',
    beneficiaries_proxy: 'Proxy',
    beneficiaries_select_api: 'API اختر',
    beneficiaries_selected_project: 'selected beneficiaries:',

    // Dashboard
    dashboard_distribution_map: 'خريطة التوزيع',
    dashboard_recent_distributions: 'التوزيعات الحديثة',
    dashboard_summary: 'الملخص',
    dashboard_summary_1: 'مجموع المستفيدين',
    dashboard_summary_2: 'المشاريع الناشطة',
    dashboard_summary_3: 'المستفيدين المسجلين',
    dashboard_summary_4: ' القيمة الإجمالية للمعملات',

    // Data verification
    data_verification_chip_actual: 'المنزل المستهدف',
    data_verification_chip_add: 'للإضافة',
    data_verification_chip_existing: 'موجد',
    data_verification_chip_old: 'قديم',
    data_verification_chip_remove: 'للحذف',
    data_verification_description1: 'تعرض هذه اللوحة أي أخطاء كتابة مشكوك فيها تتعلق بالمستفيدين في ملف: إذا كان المستفيد المستورد يتطابق بشكل وثيق مع آخر موجود بالفعل في قاعدة البيانات ، فسيتم عرضه هنا. يمكنك اختيار إما الحفاظ على القائمة ، وتحديثها مع البيانات المستوردة أو حفظ كلاهما كمستفيدين منفصلين.',
    data_verification_description2: 'تعرض لوحة التكرار المستفيدين في الملف الموجودين بالفعل في قاعدة البيانات في منزل آخر. إذا كان المستفيد الحالي ليس رب أسرة ، يمكنك حذف احداهما ، أو حفظ كلاهما كمستفيدين مختلفين إذا كنت متأكداً من أنهم أشخاص مختلفون.',
    data_verification_description3: '.في ما يلي قائمة بالأسر المدرجة  في قاعدة البيانات ولكن مع عدد أقل من المستفيدين مقارنة بالملف المستورد. يمكنك التحقق وتحديد الذين تريد استيرادهم في المنزل',
    data_verification_description4: '.في ما يلي قائمة بالأسر المدرجة  في قاعدة البيانات ولكن مع عدد أكبر  من المستفيدين مقارنة بالملف المستورد. يمكنك التحقق وتحديد الذين تريد استيرادهم في المنزل',
    data_verification_description_end: 'Modifications will be added to the database on each step validation.',
    data_verification_done: 'تم التحقق من بياناتك',
    data_verification_error: 'حدث خطأ في معالجة البيانات',
    data_verification_send: 'أرسل',
    data_verification_snackbar_duplicate_corrected: 'أخطاء التكرار المصححة',
    data_verification_snackbar_duplicate_no_corrected: 'كل أخطاء التكرار التي لم يتم تصحيحها',
    data_verification_snackbar_less_corrected: 'تم حذف المستفيدين بنجاح',
    data_verification_snackbar_more_corrected: 'تم إضافة المستفيدين بنجاح',
    data_verification_snackbar_typo_corrected: 'أخطاء الكتابة التي تم تصحيحها',
    data_verification_snackbar_typo_no_corrected: 'كل أخطاء الكتابة التي لم يتم تصحيحها',
    data_verification_step_info: 'Step info',
    data_verification_step_1: 'أخطاء في كتابة المعلومات',
    data_verification_step_2: 'التأكد من التكرار',
    data_verification_step_3: 'للإضافة',
    data_verification_step_4: 'للحذف',
    data_verification_step_1_no_issues: 'لا يوجد أخطاء في كتابة المعلومات',
    data_verification_step_2_no_issues: 'لا يوجد تكرار في كتابة المعلومات',
    data_verification_step_3_no_issues: 'لا يوجد مستفيدون للإضافة',
    data_verification_step_4_no_issues: 'لا يوجد مستفيدون للحذف',
    data_verification_title: 'التحقق من صحة البيانات و الموافقة',

    // Distribution
    distribution_accept_changed: 'Accept Changes',
    distribution_add_beneficiaries: 'Add beneficiaries to this distribution',
    distribution_beneficiary_added: 'تم أضافة المستفيد',
    distribution_beneficiary_not_added: 'لم بتم أضافة المستفيد',
    distribution_cant_update: 'You can\'t update this distribution.',
    distribution_details_export: 'قائمة التوزيع',
    distribution_details_import: 'تحميل والمقارنة',
    distribution_details_random: 'عينة عشوائية للتحميل',
    distribution_details_sample_size: 'حجم العينة',
    distribution_details_validate: 'التحقق والقفل',
    distribution_no_beneficiaries: 'No beneficiaries have been added or removed. Any changes made to the imported beneficiaries will be updated in the system.',
    distribution_no_random_sample: 'Random sample can\'t be generated...',
    distribution_no_right_transaction: 'لا يحق لك أن تقوم بالصفقة ، اسأل مدير المشروع الخاص بك أو مدير بلدك',
    distribution_no_right_validate: 'لا يحق لك التحقق من صحة التوزيع ، اسأل مدير المشروع الخاص بك',
    distribution_no_valid_commodity: 'لم يتم اكتشاف سلعة صالحة لهذا التوزيع',
    distribution_not_modified: 'This distribution has not been modified so far.',
    distribution_not_validated: 'لا يمكن التحقق من صحة التوزيع ',
    distribution_request_logs: 'Send transaction logs by email',
    distribution_select_beneficiaries: 'Please select the beneficiaries from the project',
    distribution_show_data: 'Show data anyway',
    distribution_validate: 'Validate',
    distribution_validated: ' تم التحقق من صحة التوزيع',
    distribution_want_add: 'that you want to add to the ',

    // Header
    'header_add-beneficiaries': 'إضافة المستفيد',
    'header_add-distribution': 'إضافة توزيع',
    header_beneficiaries: 'المستفيدون',
    'header_data-validation': 'التأكد من صحة البيانات',
    header_disconnect:  'تسجيل الخروج من الحساب',
    'header_distributions': 'التوزيع',
    header_home: 'الصفحة الرئيسية',
    header_import:  'تحميل بيانات المستفيد',
    header_imported: 'إستيراد بيانات المستفيدين',
    header_language: 'اللغة',
    header_profile: ' المعطيات الشخصية',
    header_projects: 'المشاريع',
    header_reports: 'التقارير',
    header_settings: 'الإعدادات',
    'header_update-beneficiary': 'تحديث المستفيد',

    // Import
    import_added: 'تم إضافتها',
    import_created: 'تم إنشاؤها',
    import_deleted: 'تم حذفها',
    import_description: 'قم باستيراد الملف الذي يحتوي على التوزيع المعدّل. سيتم تحديث قاعدة البيانات بقائمة المستفيدين الجديدة لهذا التوزيع عندما تنقر على ""تحديث"" بعد الاستيراد.',
    import_distribution_no_right_update: 'لا يحق لك تحديث التوزيع ، اسأل مدير المشروع الخاص بك',
    import_distribution_updated: 'تم تحديث التوزيع',
    import_updated: 'تم تحديثها',

    // Login
    login_bms: 'نظام إدارة المستفيدين',
    login_forgot_password: 'هل نسيت كلمة المرور',
    login_password: 'كلمة المرور',
    login_title: ' تسجيل الدخول الى الحساب',
    login_username: 'اسم المستخدم',

    // Modal
    modal_add_bad_weight: 'يجب أن يكون الوزن أكبر من 0',
    modal_add_check_fields_budget: 'تحقق جيدا انك أدخلت جميع المعطيات و ان المبلغ يفوق 0',
    modal_add_check_fields_quantity: 'تحقق جيدا انك أدخلت جميع المعطيات و ان الكمية تفوق 0 ',
    modal_add_fail_criteria: 'خطأ في انشاء معيار',
    modal_add_invalid_mail: ' عليك بادخال البريد الالكتروني ',
    modal_add_no_right: 'عليك بتحديد الحق',
    modal_add_no_value: 'عليك بادخال قيمة عددية',
    modal_add_title: 'إضافة جديد',
    modal_check_date: 'الحقول غير الصالح: لا يمكن أن يكون تاريخ الانتهاء  أقدم من تاريخ البدء',
    modal_check_fields: 'تحقق جيدا انك أدخلت جميع المعطيات',
    modal_delete_sentence: 'أنت على وشك الحذف',
    modal_delete_sentence_2: 'هل أنت متأكد',
    modal_email_is: 'البريد الالكتروني هو',
    modal_language_actual: 'اللغة الحالية',
    modal_failure: 'Failure',
    modal_leave: 'المغادرة',
    modal_leave_sentence: 'هل تريد حقا أن تغادر دون حفظ التغييرات',
    modal_language_title: 'اللغة',
    modal_no_country: 'عليك بتحديد بلد على الأقل يتعلق بالحق',
    modal_no_password: 'عليك بادخال كلمة المرور ',
    modal_not_enough_strong: 'The password is not strong enough... Minimum required: 8 characters, 1 lowercase, 1 uppercase, 1 numeric',
    modal_no_project: 'عليك بتحديد مشروع على الأقل يتعلق بالحق',
    modal_pending_requests: 'Pending Requests',
    modal_success: 'Success',
    modal_required: 'مطلوب',
    modal_valid_email: 'من فضلك أدخل البريد الكتروني الصحيح',
    modal_warning_pending_requests_1: 'Find the requests you created during your offline time below, you can send those you want to apply to modify the database.',
    modal_warning_pending_requests_2: 'WARNING: Requests linked to an item you created offline will fail !',


    // Model
    model_beneficiaries_dependents: 'التوابع',
    model_beneficiaries_nationalids: 'رقم الهوية',
    model_beneficiaries_phones: 'الهاتف',
    model_beneficiaries_status: 'الرتبة في الأسرة',
    model_commodity: 'السلع',
    model_commodity_modality: 'القيد',
    model_commodity_unit: 'وحدة',
    model_commodity_value: 'كمية',
    model_country_specific: 'خيار حسب بالبلد',
    model_country_specific_field: 'الميدان',
    model_countryIso3: 'البلد',
    model_criteria: 'المعاير',
    model_criteria_operator: 'الشروط',
    model_criteria_weight: 'وزن النتيجة',
    model_dateofbirth: 'تاريخ الميلاد',
    model_distribution_date: 'تاريخ التوزيع',
    model_distribution_name: 'الاسم',
    model_distribution_type: 'العالمي',
    model_donor: 'المانح',
    model_donor_fullname: 'اسم المانح',
    model_donor_shortname: 'الاسم المختصر',
    model_familyName: 'اللقب',
    model_firstName: 'الاسم ',
    model_notes: 'الملاحظات',
    model_project_end_date: 'تاريخ الانتهاء',
    model_project_donors_name: 'المانحون',
    model_project_name: 'اسم المشروع',
    model_project_number_of_households: 'عدد الأسر',
    model_project_start_date: 'تاريخ البداية',
    model_project_value: 'المبلغ الموزع',
    model_sector: 'القطاع',
    model_sectors_name: 'القطاعات',
    model_transaction_message: 'Message',
    model_transaction_pickupDate: 'Pick up date',
    model_type: 'النوع',
    model_vulnerabilities: 'نقاط الضعف',
    model_user: 'المستخدم',
    model_user_password: 'كلمة المرور',
    model_value: 'القيمة',
    model_transaction_state: 'الحالة',

    // Profile
    profile_user_change_password: 'تغيير كلمة المرور',
    profile_user_hint_new_password: 'كلمة المرور الجديدة',
    profile_user_hint_new_password_again: 'أعد إدخال كلمة المرور الجديدة',
    profile_user_hint_old_password: 'كلمة المرور القديمة',
    profile_user_information: 'معلومات المستخدم',

    // Project
    project_add: 'Please add some projects first ! Then you will be able to manage some distributions...',
    project_add_household: 'Please add some beneficiaries first ! Then you will be able to manage some distributions...',
    project_click: 'Click on',
    project_create: 'Create a new project',
    project_description: 'سوف يمكنك تعديل اسم المشروع حتى توزيعك الأول',
    project_go_beneficiaries: 'Go to Beneficiaries',
    project_no_distribution: 'This project does not contain any distributions. Create your first one !',
    project_no_household: 'This project does not contain any household.',
    project_no_projects: 'This country does not contain any project.',

    // Report
    report_apply: 'تطبيق',
    report_country: ' البلد',
    report_country_report: 'الرسوم البيانية حسب البلد',
    report_distribution: ' التوزيع',
    report_distribution_report: 'الرسوم البيانية حسب التوزيع',
    report_filter_per_month: 'حسب كل شهر',
    report_filter_chose_periode: 'اختر الفترة',
    report_filter_per_quarter: 'حسب كل ربع سنة',
    report_filter_per_year: 'حسب كل سنة ',
    report_frequency_month: ' حسب الشهر',
    report_frequency_quarter: 'حسب ربع السنة ',
    report_frequency_year: ' حسب السنة  ',
    report_from: 'من',
    report_loader: 'التحميل',
    report_period_selected: 'حسب الفترة المختارة',
    report_project:  'المشروع',
    report_project_report: 'الرسوم البيانية حسب المشروع',
    report_select_frequency: 'اختر التكرار',
    report_to: 'إلى',
    report_upcoming_reporting: 'الرسوم البيانية القادمة',

    // Settings
    settings_country_specific_options: 'الخيارات حسب البلد',
    settings_created: 'تم انشاء ',
    settings_donors: 'المانحين',
    settings_financial_provider: 'Financial provider',
    settings_log_button: 'Get user logs by email',
    settings_project_exists: 'مشروع بهذا الاسم يوجود بالفعل',
    settings_users: 'المستخدمون',

    // Snackbar
    snackbar_change_password_done: '!تم تغيير كلمة المرور',
    snackbar_change_password_fail: '...لا يمكن تغيير كلمة المرور',
    snackbar_change_password_not_possible: 'يجب أن تكون كلمة المرور أطول من حرف واحد وتتطابق مع الشروط',

    // Table
    table_actions: 'اجراءات',
    table_element_deleted: ' تم حذفها',
    table_element_updated: ' تم تحديثها',
    table_filter: 'البحث عن طريق الكلمات الرئيسية',
    table_first_page: 'الصفحة الأولى',
    table_items_per_page: 'العناصر في كل صفحة',
    table_last_page: 'الصفحة الاخيرة',
    table_next_page: 'الصفحة التالية',
    table_of_page: 'من',
    table_previous_page: 'الصفحة السابقة',

    // Transaction
    transaction_accept_prevention: 'I agree to these terms.',
    transaction_again: 'Send again',
    transaction_amount_done: 'Amount picked up',
    transaction_amount_total: 'الكمية الإجمالية',
    transaction_amount_waiting: 'Still to be picked up',
    transaction_confirm: 'Confirm the transaction',
    transaction_confirm_button: 'Confirm',
    transaction_email_code: 'An email containing your validation code has been sent to:',
    transaction_paste_code: 'Please paste the code here and click on \'Confirm\' to proceed with the transaction: ',
    transaction_prevention: 'This platform is still under development and the online cash transaction functionality may not be fully stable yet. The development team denies responsibility for any errors that may occur in terms of money loss. By ticking the box below, you agree to use the system knowing fully well its limitations and take responsibility for the results of the transaction.',
    transaction_progress: 'commodity distribution progress:',
    transaction_refresh: 'Check pickup status',
    transaction_transaction: 'Transaction',
    transaction_validate_distribution: 'Do you really want to validate this distribution ? You won\'t be able to modify it anymore.',
    transaction_validation: 'Confirm the validation',
    transaction_inProgress: 'Transaction in progress...',

    // Tooltip
    tooltip_add_beneficiaries: 'This page is the add beneficiaries\' page. This is a form to add a new household with required fields.',
    tooltip_add_distribution: 'This page is the add distribution\'s page. This is a form to add a new distribution with required fields. You will select households or beneficiaries by sorting them by a selection criteria and add a specific amount of commodities to the distribution.',
    tooltip_beneficiaries: 'This page is the beneficiaries\' page. You can see all households of the country. If you have the right, you can add new households with the "+" button, manage households and research in the list.',
    tooltip_dashboard: 'This page is the dashboard. You have a global view on some numbers about the country and its projects. You have access to a map with distributions of the country and summary of last distributions.',
    tooltip_data: 'This page is the post import beneficiaries\' page. This is a summary of households you have imported.',
    tooltip_data_validation: 'This page is the import beneficiaries\' page using a file. You have to verify your file by following the steps.',
    tooltip_distributions: 'This page is the distribution\'s page. You can see all households of the distribution. If you have the right, you can add new households with a file or by selecting in the list, manage households and validate the distribution to a transaction.',
    tooltip_import: 'This page is the import beneficiaries\' page. You can choose to import new households using a file or the API (the external data source) to import all the household of a specific commune.',
    tooltip_profile: 'This page is the profile\'s page. You can change your password.',
    tooltip_projects: 'This page is the projects\' page. You can see all projects of the country (only thoses that you have the right to see). If you have the right, you can add a new distribution with households whose are in the project, manage distributions and transactions.',
    tooltip_reports: 'This page is the reports\' page. This page is used to see statistics of the country, like the average transactions of a projects, number of distributions...',
    tooltip_settings: 'This page is the settings\' page. In this page, you\'ll be able to add a new user, new country specifics, new donors, a new project and change the credential for the transaction.',
    tooltip_update_beneficiary: 'This page is the update beneficiaries\' page. This is a form to update the selected household with required fields.',

    // Update beneficiary
    update_beneficiary_check_steps: 'البيانات المطلوبة غير كاملة أو غير صالح: يرجى التحقق من جميع المراحل',
    update_beneficiary_created_successfully: 'تم الإنشاء بنجاح!',
    update_beneficiary_error_creating: ': حدث خطأ أثناء الإنشاء ',
    update_beneficiary_error_updated: ': حدث خطأ أثناء التحديث',
    update_beneficiary_title: 'تحديث المستفيدين',
    update_beneficiary_updated_successfully: ' !تم التحديث بنجاح',
};
