export const TEXT = {
    dashboard_distribution_map : "repartition des distributions",
    dashboard_country_program : "programmes au Cambodge",
    dashboard_summary : "sommaire",
    dashboard_summary_1 : "total de bénéficiaires",
    dashboard_summary_2 : "projets en cours",
    dashboard_summary_3 : "bénéficiaires enregistrés",
    dashboard_summary_4 : "montant total des transactions",
    dashboard_recent_distributions : "distributions récentes",

    menu_distributions : "distributions", 
    menu_households : "ménages",
    menu_reports : "graphiques",
    menu_settings : "paramètres",

    header_home : "Accueil",
    header_profile : "profil", 
    header_disconnect : "déconnexion",
    header_language : "langue",

    login_title : "login",
    login_bms : "Beneficiary management system",
    login_username : "identifiant",
    login_password : "*********",
    login_login : "connexion",
    login_forgot_password : "Mot de passe oublié ?",

    settings_title : "paramètres",
    settings_users : "utilisateurs",
    settings_country_specific_options : "options par pays",
    settings_donors : "donneurs",
    settings_projects : "projets",
    settings_export : "export",

    report_title : "graphiques",
    report_filter_per_year : "par année",
    report_filter_per_quarter : "par trimestre",
    report_filter_per_month : "par mois",
    report_filter_chose_periode : "choisir période",
    report_export : "export",
    report_from : "de",
    report_to : "à",
    report_apply : "appliquer",
    report_select_frequency : "Choisir fréquence",
    report_frequency_year : "Année",
    report_frequency_quarter : "Trimestre",
    report_frequency_month : "Mois",
    report_period_selected : "période choisie",
    report_country_report : "graphiques par pays",
    report_project_report : "graphiques par projet",
    report_distribution_report : "graphiques par distribution",
    report_country : "par pays",
    report_project : "par projet",
    report_distribution : "par distribution",
    report_upcoming_reporting : "Graphiques à venir",
    report_loader : "Chargement",

    households_title : "ménages",
    households_export : "export",
    households_import : "import",

    distribution_title : "distributions",
    distribution_export : "export",
    
    add_distribution_title : "nouvelle distribution",
    add_distribution_new_distribution : "nouvelle distribution",
    add_distribution_selection_criteria : "critères de sélection",
    add_distribution_distributed_commodity : "ressource distribuée",
    add_distribution_beneficiaries_reached: "Bénéficaires atteints",
    add_distribution_commodities_delivered: "Ressources délivrées",
    add_distribution_create_error: "créer une distribution sera bientôt possible !",

    table_filter : "Filtre",
    table_actions : "Actions",
    table_items_per_page : "Items par page",
    table_first_page : "Début",
    table_previous_page : "Page précédente",
    table_next_page : "Page suivante",
    table_last_page : "Fin",
    table_of_page : "sur",

    modal_details_title : "Détails",
    modal_update_title : "Modifier",
    modal_add_title : "Ajouter un nouveau",
    modal_delete_title : "Supprimer",
    modal_language_title : "Langage",
    modal_language_actual : "Langue courante :",
    modal_delete_sentence : "Vous êtes sur le point de supprimer ",
    modal_delete_sentence_2 : ". ",
    modal_close : "Fermer",
    modal_cancel : "Annuler",
    modal_save : "Enregistrer",
    modal_delete : "Supprimer",
    modal_create : "Créer", 
    modal_valid_email : "Veuillez utiliser un mail valide",
    modal_email_is : "Email ",
    modal_email_placeholder : "Email",
    modal_required : "obligatoire",

    model_country_specific : "Option par pays",
    model_country_specific_field: "Champ",
    model_country_specific_type: "Type",
    model_country_specific_countryIso3: "Pays",
    model_distribution : "Distribution",
    model_distribution_name: "Nom",
    model_distribution_location_name: "Lieu",
    model_distribution_number_beneficiaries: "n° Bénéficiaires",
    model_distribution_sectors_name: "Secteurs",
    model_distribution_adm1: "Province",
    model_distribution_adm2: "District",
    model_distribution_adm3: "Commune",
    model_distribution_adm4: "Village",
    model_donor : "Donneur",
    model_donor_fullname: "Nom du donneur",
    model_donor_shortname: "Surnom",
    model_donor_notes: "Notes",
    model_donor_projects_name: "Projets",
    model_households : "Ménage",
    model_households_familyName: "Nom",
    model_households_firstName: "Prénom",
    model_households_location: "Lieu",
    model_households_dependents : "Dépendents",
    model_households_vulnerabilities : "Vulnérabilités",
    model_user : "Utilisateur",
    model_user_username: "Email",
    model_user_rights: "Rôles",
    model_project : "Projet",
    model_project_name: "Nom  du projet",
    model_project_sectors_name: "Secteurs",
    model_project_start_date: "Date de début de projet",
    model_project_end_date: "Date de fin de projet",
    model_project_number_of_households: "Nombre de ménages",
    model_project_donors_name: "Donneurs",
    model_project_notes: "Notes",
    model_project_value: "Budget",
    model_sector : "Secteur",
    model_criteria : "Critère",
    model_criteria_kind_beneficiary : "Groupe",
    model_criteria_field : "Critère",
    model_criteria_operator : "Condition",
    model_criteria_value : "Valeur",
    model_commodity: "Ressource",
    model_commodity_modality: "Modalité",
    model_commodity_type: "Type",
    model_commodity_unit: "Unité",
    model_commodity_value: "Quantité"
}