export const TEXT = {
    dashboard_distribution_map : 'مرحبا',
    dashboard_country_program : 'مرحبا',
    dashboard_summary : 'مرحبا',
    dashboard_summary_1 : 'مرحبا',
    dashboard_summary_2 : 'مرحبا',
    dashboard_summary_3 : 'مرحبا',
    dashboard_summary_4 : 'مرحبا',
    dashboard_recent_distributions : 'مرحبا',

    menu_home : 'مرحبا',
    menu_projects : 'مرحبا',
    menu_beneficiaries : 'مرحبا',
    menu_reports : 'مرحبا',
    menu_settings : 'مرحبا',

    header_home : 'مرحبا',
    header_projects : 'مرحبا',
    'header_add-distribution' : 'مرحبا',
    'header_distributions' : 'مرحبا',
    'header_update-beneficiary' : 'مرحبا',
    header_beneficiaries : 'مرحبا',
    header_resports : 'مرحبا',
    header_settings : 'مرحبا',
    header_reports : 'مرحبا',
    header_profile : 'مرحبا',
    header_import : 'مرحبا',
    'header_data-validation' : 'مرحبا',
    'header_add-beneficiaries' : 'مرحبا',
    header_disconnect : 'مرحبا',
    header_language : 'مرحبا',

    login_title : 'مرحبا',
    login_bms : 'مرحبا',
    login_username : 'مرحبا',
    login_password : 'مرحبا',
    login_login : 'مرحبا',
    login_forgot_password : 'مرحبا',

    settings_title : 'مرحبا',
    settings_users : 'مرحبا',
    settings_country_specific_options : 'مرحبا',
    settings_donors : 'مرحبا',
    settings_projects : 'مرحبا',
    settings_export : 'مرحبا',

    report_title : 'مرحبا',
    report_filter_per_year : 'مرحبا',
    report_filter_per_quarter : 'مرحبا',
    report_filter_per_month : 'مرحبا',
    report_filter_chose_periode : 'مرحبا',
    report_export : 'مرحبا',
    report_from : 'مرحبا',
    report_to : 'مرحبا',
    report_apply : 'مرحبا',
    report_select_frequency : 'مرحبا',
    report_frequency_year : 'مرحبا',
    report_frequency_quarter : 'مرحبا',
    report_frequency_month : 'مرحبا',
    report_period_selected : 'مرحبا',
    report_country_report : 'مرحبا',
    report_project_report : 'مرحبا',
    report_distribution_report : 'مرحبا',
    report_country : 'مرحبا',
    report_project : 'مرحبا',
    report_distribution : 'مرحبا',
    report_upcoming_reporting : 'مرحبا',
    report_loader : 'مرحبا',

    beneficiaries_title : 'مرحبا',
    beneficiaries_export : 'مرحبا',

    beneficiaries_import : 'مرحبا',
    beneficiaries_import_file : 'مرحبا',
    beneficiaries_import_api : 'مرحبا',
    beneficiaries_select_api : 'مرحبا',
    beneficiaries_import_title: 'مرحبا',
    beneficiaries_import_getProject: 'مرحبا',
    beneficiaries_import_csv: 'مرحبا',
    beneficiaries_import_addFile: 'مرحبا',
    beneficiaries_import_upload: 'مرحبا',

    add_beneficiary_title: 'مرحبا',
    add_beneficiary_step1: 'مرحبا',
    add_beneficiary_step2: 'مرحبا',
    add_beneficiary_step3: 'مرحبا',
    add_beneficiary_step4: 'مرحبا',
    add_beneficiary_done: 'مرحبا',
    add_beneficiary_create: 'مرحبا',
    add_beneficiary_cancel: 'مرحبا',
    add_beneficiary_next: 'مرحبا',
    add_beneficiary_getProject: 'مرحبا',
    add_beneficiary_getProvince: 'مرحبا',
    add_beneficiary_getDistrict: 'مرحبا',
    add_beneficiary_getCommune: 'مرحبا',
    add_beneficiary_getVillage: 'مرحبا',
    add_beneficiary_getAddressNumber: 'مرحبا',
    add_beneficiary_getAddressStreet: 'مرحبا',
    add_beneficiary_getAddressPostcode: 'مرحبا',
    add_beneficiary_getNotes : 'مرحبا',
    add_beneficiary_getFamilyName : 'مرحبا',
    add_beneficiary_getGivenName : 'مرحبا',
    add_beneficiary_getGender : 'مرحبا',
    add_beneficiary_getDateOfBirth : 'مرحبا',
    add_beneficiary_getNationalID : 'مرحبا',
    add_beneficiary_getOccupation : 'مرحبا',
    add_beneficiary_getTypeNationalId: 'مرحبا',
    add_beneficiary_getTypePhone: 'مرحبا',
    add_beneficiary_getPhone: 'مرحبا',
    add_beneficiary_Country_Specifics: 'مرحبا',

    update_beneficiary_title: 'مرحبا',

    data_verification_title: 'مرحبا',
    data_verification_step_1: 'مرحبا',
    data_verification_step_2: 'مرحبا',
    data_verification_step_3: 'مرحبا',
    data_verification_step_4: 'مرحبا',
    data_verification_step_5: 'مرحبا',
    data_verification_step_1_no_issues: 'مرحبا',
    data_verification_step_2_no_issues: 'مرحبا',
    data_verification_step_3_no_issues: 'مرحبا',
    data_verification_step_4_no_issues: 'مرحبا',
    data_verification_done: 'مرحبا',
    data_verification_chip_existing: 'مرحبا',
    data_verification_chip_new: 'مرحبا',
    data_verification_chip_old: 'مرحبا',
    data_verification_chip_add: 'مرحبا',
    data_verification_chip_remove: 'مرحبا',
    data_verification_next: 'مرحبا',
    data_verification_send: 'مرحبا',
    data_verification_snackbar_typo_corrected: 'مرحبا',
    data_verification_snackbar_typo_no_corrected: 'مرحبا',
    data_verification_snackbar_duplicate_corrected: 'مرحبا',
    data_verification_snackbar_duplicate_no_corrected: 'مرحبا',
    data_verification_snackbar_less_corrected: 'مرحبا',
    data_verification_snackbar_more_corrected: 'مرحبا',

    distribution_title : 'مرحبا',
    distribution_export : 'مرحبا',
    project_title: 'مرحبا',

    add_project_title : 'مرحبا',
    add_project_new_distribution : 'مرحبا',
    add_distribution_selection_criteria : 'مرحبا',
    add_distribution_distributed_commodity : 'مرحبا',
    add_distribution_beneficiaries_reached: 'مرحبا',
    add_distribution_households_reached: 'مرحبا',
    add_distribution_commodities_delivered: 'مرحبا',
    add_distribution_threshold: 'مرحبا',
    add_distribution_text_explanation: 'مرحبا',
    add_distribution_female: 'مرحبا',
    add_distribution_male: 'مرحبا',
    add_project: 'مرحبا',

    table_filter : 'مرحبا',
    table_actions : 'مرحبا',
    table_items_per_page : 'مرحبا',
    table_first_page : 'مرحبا',
    table_previous_page : 'مرحبا',
    table_next_page : 'مرحبا',
    table_last_page : 'مرحبا',
    table_of_page : 'مرحبا',
    table_quantity : 'مرحبا',

    modal_details_title : 'مرحبا',
    modal_update_title : 'مرحبا',
    modal_add_title : 'مرحبا',
    modal_delete_title : 'مرحبا',
    modal_language_title : 'مرحبا',
    modal_language_actual : 'مرحبا',
    modal_delete_sentence : 'مرحبا',
    modal_delete_sentence_2 : 'مرحبا',
    modal_close : 'مرحبا',
    modal_cancel : 'مرحبا',
    modal_save : 'مرحبا',
    modal_delete : 'مرحبا',
    modal_create : 'مرحبا',
    modal_add : 'مرحبا',
    modal_valid_email : 'مرحبا',
    modal_email_is : 'مرحبا',
    modal_email_placeholder : 'مرحبا',
    modal_required : 'مرحبا',
    modal_leave : 'مرحبا',
    modal_leave_sentence : 'مرحبا',

    model_country_specific : 'مرحبا',
    model_country_specific_field: 'مرحبا',
    model_country_specific_type: 'مرحبا',
    model_country_specific_countryIso3: 'مرحبا',
    model_distribution : 'مرحبا',
    model_distribution_name: 'مرحبا',
    model_distribution_location_name: 'مرحبا',
    model_distribution_number_beneficiaries: 'مرحبا',
    model_distribution_sectors_name: 'مرحبا',
    model_distribution_adm1: 'مرحبا',
    model_distribution_adm2: 'مرحبا',
    model_distribution_adm3: 'مرحبا',
    model_distribution_adm4: 'مرحبا',
    model_distribution_date: 'مرحبا',
    model_donor : 'مرحبا',
    model_donor_fullname: 'مرحبا',
    model_donor_shortname: 'مرحبا',
    model_donor_notes: 'مرحبا',
    model_donor_projects_name: 'مرحبا',
    model_households : 'مرحبا',
    model_beneficiaries_familyName: 'مرحبا',
    model_beneficiaries_firstName: 'مرحبا',
    model_beneficiaries_location: 'مرحبا',
    model_beneficiaries_dependents : 'مرحبا',
    model_beneficiaries_vulnerabilities : 'مرحبا',
    model_beneficiaries_projects : 'مرحبا',
    model_beneficiaries_gender : 'مرحبا',
    model_beneficiaries_dateofbirth : 'مرحبا',
    model_beneficiaries_status: 'مرحبا',
    model_beneficiaries_nationalids: 'مرحبا',
    model_beneficiaries_phones: 'مرحبا',
    model_user : 'مرحبا',
    model_user_username: 'مرحبا',
    model_user_password: 'مرحبا',
    model_user_rights: 'مرحبا',
    model_project : 'مرحبا',
    model_project_name: 'مرحبا',
    model_project_sectors_name: 'مرحبا',
    model_project_start_date: 'مرحبا',
    model_project_end_date: 'مرحبا',
    model_project_number_of_households: 'مرحبا',
    model_project_donors_name: 'مرحبا',
    model_project_notes: 'مرحبا',
    model_project_value: 'مرحبا',
    model_sector : 'مرحبا',
    model_criteria : 'مرحبا',
    model_criteria_kind_beneficiary : 'مرحبا',
    model_criteria_field : 'مرحبا',
    model_criteria_operator : 'مرحبا',
    model_criteria_value : 'مرحبا',
    model_criteria_beneficiary : 'مرحبا',
    model_criteria_household : 'مرحبا',
    model_criteria_weight : 'مرحبا',
    model_commodity: 'مرحبا',
    model_commodity_modality: 'مرحبا',
    model_commodity_type: 'مرحبا',
    model_commodity_unit: 'مرحبا',
    model_commodity_value: 'مرحبا',
    model_commodity_currency: 'مرحبا',
    model_beneficiaries_state: 'مرحبا',
    model_beneficiaries_values: 'مرحبا',
    sample_choose_size: 'مرحبا',

    import_added: 'مرحبا',
    import_deleted: 'مرحبا',
    import_created: 'مرحبا',
    import_updated: 'مرحبا',
    import_description: 'مرحبا',

    distribution_details_export: 'مرحبا',
    distribution_details_import: 'مرحبا',
    distribution_details_random: 'مرحبا',
    distribution_details_validate: 'مرحبا',
    transaction_amount_total: 'مرحبا',
    transaction_amount_done: 'مرحبا',
    transaction_amount_waiting: 'مرحبا',

    profile_user_information: 'مرحبا',
    profile_user_change_password: 'مرحبا',
    profile_user_hint_old_password: 'مرحبا',
    profile_user_hint_new_password: 'مرحبا',
    profile_user_hint_new_password_again: 'مرحبا',
    snackbar_change_password_done: 'مرحبا',
    snackbar_change_password_fail: 'مرحبا',
    snackbar_change_password_not_possible: 'مرحبا',

    forbidden: 'مرحبا',
    forbidden_message: 'مرحبا',
    not_found: 'مرحبا',
    not_found_message: 'مرحبا',
    back_to_homepage: 'مرحبا',

    role_user_admin: 'مرحبا',
    role_user_read_only: 'مرحبا',
    role_user_field_officer: 'مرحبا',
    role_user_project_officer: 'مرحبا',
    role_user_project_manager: 'مرحبا',
    role_user_country_manager: 'مرحبا',
    role_user_regional_manager: 'مرحبا',
    role_user_global_admin: 'مرحبا'
};
