export const TEXT = {
    dashboard_distribution_map : "repartition des distributions",
    dashboard_country_program : "programmes au Cambodge",
    dashboard_summary : "sommaire",
    dashboard_summary_1 : "total de bénéficiaires",
    dashboard_summary_2 : "projets en cours",
    dashboard_summary_3 : "bénéficiaires enregistrés",
    dashboard_summary_4 : "montant total des transactions",
    dashboard_recent_distributions : "distributions récentes",

    menu_distributions : "distributions", 
    menu_households : "ménages",
    menu_reports : "graphiques",
    menu_settings : "paramètres",

    header_home : "Accueil",
    header_profile : "profil", 
    header_disconnect : "se connecter",

    login_bms : "Beneficiary management system",
    login_username : "identifiant",
    login_password : "*********",
    login_login : "se connecter",
    login_forgot_password : "Mot de passe oublié ?",

    settings_title : "paramètres",
    settings_users : "utilisateurs",
    settings_country_specific_options : "options par pays",
    settings_donors : "donneurs",
    settings_projects : "projets",
    settings_export : "export",

    table_filter : "Filtre",
    table_actions : "Actions",
    table_items_per_page : "Items par page",
    table_first_page : "Début",
    table_previous_page : "Page précédente",
    table_next_page : "Page suivante",
    table_last_page : "Fin",
    table_of_page : "sur",

    modal_details_title : "Détails",
    modal_update_title : "Modifier",
    modal_add_title : "Ajouter un nouveau",
    modal_delete_title : "Supprimer",
    modal_delete_sentence : "Vous êtes sur le point de supprimer ",
    modal_delete_sentence_2 : ". ",
    modal_close : "Fermer",
    modal_cancel : "Annuler",
    modal_save : "Enregistrer",
    modal_delete : "Supprimer",
    modal_create : "Créer", 
    modal_valid_email : "Veuillez utiliser un mail valide",
    modal_email_is : "Email ",
    modal_email_placeholder : "Email",
    modal_required : "obligatoire",

    model_country_specific : "Option par pays",
    model_country_specific_field: "Champ",
    model_country_specific_type: "Type",
    model_country_specific_countryIso3: "Pays",
    model_distribution : "Distribution",
    model_distribution_name: "Distribution",
    model_distribution_location_name: "Lieu",
    model_distribution_number_beneficiaries: "n° Bénéficiaires",
    model_distribution_sectors_name: "Secteurs",
    model_donor : "Donneur",
    model_donor_fullname: "Nom du donneur",
    model_donor_shortname: "Surnom",
    model_donor_notes: "Notes",
    model_donor_projects_name: "Projets",
    model_households : "Ménage",
    model_households_familyName: "Nom",
    model_households_firstName: "Prénom",
    model_households_location: "Lieu",
    model_households_dependents : "Dépendents",
    model_households_vulnerabilities : "Vulnérabilités",
    model_user : "Utilisateur",
    model_user_username: "Email",
    model_user_rights: "Rôles",
    model_project : "Projet",
    model_project_name: "Nom  du projet",
    model_project_sectors_name: "Secteurs",
    model_project_start_date: "Date de début de projet",
    model_project_end_date: "Date de fin de projet",
    model_project_number_of_households: "Nombre de ménages",
    model_project_donors_name: "Donneurs",
    model_project_notes: "Notes",
    model_sector : "Secteur"
}