export const TEXT = {
    dashboard_distribution_map : "distribution map",
    dashboard_country_program : "cambodia programs",
    dashboard_summary : "summary",
    dashboard_summary_1 : "total beneficiaries",
    dashboard_summary_2 : "active projects",
    dashboard_summary_3 : "enrolled beneficiaries",
    dashboard_summary_4 : "total value transactions",
    dashboard_recent_distributions : "recent distributions",

    menu_distributions : "distributions", 
    menu_households : "households",
    menu_reports : "reports",
    menu_settings : "settings",

    header_home : "Home",
    header_profile : "profile", 
    header_disconnect : "disconnect",
    header_language : "language",

    login_title : "login",
    login_bms : "Beneficiary management system",
    login_username : "username",
    login_password : "*********",
    login_login : "login",
    login_forgot_password : "Forgot password ?",

    settings_title : "settings",
    settings_users : "users",
    settings_country_specific_options : "country specific options",
    settings_donors : "donors",
    settings_projects : "projects",
    settings_export : "export",

    report_title : "reports",
    report_filter_per_year : "per year",
    report_filter_per_quarter : "per quarter",
    report_filter_per_month : "per month",
    report_filter_chose_periode : "choose period",
    report_export : "export",
    report_from : "from",
    report_to : "to",
    report_apply : "apply",
    report_select_frequency : "Select frequency",
    report_frequency_year : "Year",
    report_frequency_quarter : "Quarter",
    report_frequency_month : "Month",
    report_period_selected : "Period selected",
    report_country_report : "country report",
    report_project_report : "project report",
    report_distribution_report : "distribution report",
    report_country : "country",
    report_project : "project",
    report_distribution : "distribution",
    report_upcoming_reporting : "Upcoming reporting",
    report_loader : "Loader",

    households_title : "households",
    households_export : "export",

    households_import : "import",
    households_import_file : "file import",
    households_import_api : "api import",
    households_import_title: "import households data",
    households_import_getProject: 'Projects',
    households_import_csv: 'download csv template',
    households_import_addFile: 'add file or drag and drop',
    households_import_upload: 'upload',

    add_household_title: "add household",

    data_verification_title: 'data verification and validation',
    data_verification_step_1: 'Typo issues',
    data_verification_step_2: 'Duplicates',
    data_verification_step_3: 'To add',
    data_verification_step_4: 'To remove',
    data_verification_step_5: 'Done',
    data_verification_step_1_no_issues: 'No typo issues',
    data_verification_step_2_no_issues: 'No duplicate',
    data_verification_step_3_no_issues: 'No beneficiaries to add',
    data_verification_step_4_no_issues: 'No beneficiaries to remove',
    data_verification_done: 'Your data has been verified',
    data_verification_chip_existing: 'Existing',
    data_verification_chip_new: 'New',
    data_verification_chip_old: 'Old',
    data_verification_chip_add: 'To add',
    data_verification_chip_remove: 'To remove',
    data_verification_next: 'Next',
    data_verification_send: 'Send',
    data_verification_snackbar_typo_corrected: 'Typo issues corrected',
    data_verification_snackbar_typo_no_corrected: 'All typo issues aren\'t corrected',
    data_verification_snackbar_duplicate_corrected: 'Duplicate issues corrected',
    data_verification_snackbar_duplicate_no_corrected: 'All duplicates aren\'t corrected',
    data_verification_snackbar_less_corrected: 'Beneficiaries removed with success',
    data_verification_snackbar_more_corrected: 'Beneficiaries added with success',

    distribution_title : "distributions",
    distribution_export : "export",

    add_distribution_title : "new distribution",
    add_distribution_new_distribution : "new distribution",
    add_distribution_selection_criteria : "selection criteria",
    add_distribution_distributed_commodity : "distributed commodity",
    add_distribution_beneficiaries_reached: "Beneficiaries reached",
    add_distribution_commodities_delivered: "Commodities delivered",
    add_distribution_create_error: "create a distribution soon !",

    table_filter : "Filter",
    table_actions : "Actions",
    table_items_per_page : "Items per page",
    table_first_page : "First page",
    table_previous_page : "Previous page",
    table_next_page : "Next page",
    table_last_page : "Last page",
    table_of_page : "of",

    modal_details_title : "Details",
    modal_update_title : "Update",
    modal_add_title : "Add a new ",
    modal_delete_title : "Delete",
    modal_language_title : "Language",
    modal_language_actual : "Current language :",
    modal_delete_sentence : "You are about to delete ",
    modal_delete_sentence_2 : ". Are you sure ? ",
    modal_close : "Close",
    modal_cancel : "Cancel",
    modal_save : "Save",
    modal_delete : "Delete",
    modal_create : "Create", 
    modal_valid_email : "Please enter a valid email address",
    modal_email_is : "Email is",
    modal_email_placeholder : "Email",
    modal_required : "required",

    model_country_specific : "Country specific option",
    model_country_specific_field: "Field",
    model_country_specific_type: "Type",
    model_country_specific_countryIso3: "Country",
    model_distribution : "Distribution",
    model_distribution_name: "Name",
    model_distribution_location_name: "Location",
    model_distribution_number_beneficiaries: "n° Beneficiaries",
    model_distribution_sectors_name: "Sectors",
    model_distribution_adm1: "Province",
    model_distribution_adm2: "District",
    model_distribution_adm3: "Community",
    model_distribution_adm4: "Village",    
    model_donor : "Donor",
    model_donor_fullname: "Donor's name",
    model_donor_shortname: "Shortname",
    model_donor_notes: "Notes",
    model_donor_projects_name: "Projects",
    model_households : "Household",
    model_households_familyName: "Family name",
    model_households_firstName: "First name",
    model_households_location: "Location",
    model_households_dependents : "Dependents",
    model_households_vulnerabilities : "Vulnerabilities",
    model_user : "User",
    model_user_username: "Email",
    model_user_rights: "Rights",
    model_project : "Project",
    model_project_name: "Project's name",
    model_project_sectors_name: "Sectors",
    model_project_start_date: "Start Date",
    model_project_end_date: "End Date",
    model_project_number_of_households: "Number of Households",
    model_project_donors_name: "Donors",
    model_project_notes: "Notes",
    model_project_value: "Budget",
    model_sector : "Sector",
    model_criteria : "Criteria",
    model_criteria_kind_beneficiary : "Group",
    model_criteria_field : "Criteria",
    model_criteria_operator : "Condition",
    model_criteria_value : "Value",
    model_criteria_beneficiary : "Beneficiary",
    model_criteria_dependents : "Dependent",
    model_commodity: "Commodity",
    model_commodity_modality: "Modality",
    model_commodity_type: "Type",
    model_commodity_unit: "Unit",
    model_commodity_value: "Quantity"
}