export const LIVELIHOOD = [
    'Agriculture - Livestock',
    'Agriculture - Crops',
    'Agriculture – Fishing',
    'Agriculture – Other',
    'Mining',
    'Construction',
    'Manufacturing',
    'Retail',
    'Transportation',
    'Education',
    'Health Care',
    'Hospitality & Tourism',
    'Legal Services',
    'Home Duties',
    'Religious Service',
    'IT & Telecommunications',
    'Finance & Insurance',
    'Manual Labour',
    'NGO & Not for Profit',
    'Military or Police',
    'Government & Public Enterprise',
    'Garment Industry',
    'Security Industry',
    'Service Industry & Other Professionals',
    'Other'
];
