export const FONTS = [
    'Roboto',
    'Lato',
    'Open Sans Condensed',
    'Open Sans',
    'Montserrat',
    'Roboto Condensed',
    'Source Sans Pro',
    'Kodchasan',
    'Oswald',
    'Raleway',
    'Roboto Mono',
    'Merriweather',
    'Roboto Slab',
    'PT Sans',
    'Poppins',
    'Noto Sans',
    'Slabo 27px',
    'Playfair Display',
    'PT Serif',
    'Lora',
    'Muli',
];
